import type { Post } from '@/components/post-card';
import type { Comment } from '@/components/comments';

export const mockComments: Comment[] = [
  {
    id: 'c1',
    author: 'alex_tech',
    content:
      'This is a groundbreaking approach to the problem. The way they leveraged the new framework features is really clever. I especially liked how they optimized for edge cases.',
    points: 287,
    time: '3 hours ago',
    replies: [
      {
        id: 'c1-1',
        author: 'jane_dev',
        content: 'Great observation! I was thinking the same thing. The performance improvements are substantial.',
        points: 145,
        time: '2 hours ago',
        replies: [
          {
            id: 'c1-1-1',
            author: 'alex_tech',
            content: 'Right? And the documentation is surprisingly thorough too.',
            points: 72,
            time: '1 hour ago',
          },
        ],
      },
      {
        id: 'c1-2',
        author: 'code_wizard',
        content: 'The benchmarks in the repo look solid. Definitely worth checking out the implementation.',
        points: 98,
        time: '2 hours ago',
      },
    ],
  },
  {
    id: 'c2',
    author: 'startup_guy',
    content:
      'Has anyone actually used this in production yet? Would love to hear about real-world performance metrics.',
    points: 156,
    time: '4 hours ago',
    replies: [
      {
        id: 'c2-1',
        author: 'ops_expert',
        content: 'We deployed it last month. Running smoothly so far with minimal overhead.',
        points: 203,
        time: '2 hours ago',
      },
    ],
  },
  {
    id: 'c3',
    author: 'curious_dev',
    content:
      'How does this compare to the existing solutions mentioned in the industry reports? Seems like a significant step forward.',
    points: 89,
    time: '5 hours ago',
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    rank: 1,
    title: 'A new approach to AI-powered code generation that rivals ChatGPT',
    url: 'https://example.com/ai-code-gen',
    source: 'example.com',
    points: 2847,
    author: 'hn_user_1',
    time: '5 hours ago',
    comments: 487,
    category: 'AI',
    isTrending: true,
    upvoted: false,
  },
  {
    id: '2',
    rank: 2,
    title: 'Rust at scale: lessons from production systems',
    url: 'https://github.com/example/rust-scale',
    source: 'github.com',
    points: 2156,
    author: 'rust_enthusiast',
    time: '6 hours ago',
    comments: 342,
    category: 'Systems',
    isTrending: true,
    upvoted: false,
  },
  {
    id: '3',
    rank: 3,
    title: 'The future of web development: moving beyond JavaScript',
    url: 'https://blog.example.com/webdev-future',
    source: 'blog.example.com',
    points: 1953,
    author: 'frontend_guru',
    time: '7 hours ago',
    comments: 298,
    category: 'Web Dev',
    upvoted: false,
  },
  {
    id: '4',
    rank: 4,
    title: 'Show HN: A dashboard tool that makes analytics beautiful',
    url: 'https://dashboard.example.com',
    source: 'dashboard.example.com',
    points: 1847,
    author: 'indie_maker',
    time: '8 hours ago',
    comments: 267,
    category: 'Startups',
    upvoted: false,
  },
  {
    id: '5',
    rank: 5,
    title: 'Breaking: New processor architecture achieves quantum advantage in specific domains',
    url: 'https://example.com/quantum-breakthrough',
    source: 'example.com',
    points: 1723,
    author: 'science_reporter',
    time: '9 hours ago',
    comments: 512,
    category: 'Hardware',
    isTrending: true,
    upvoted: false,
  },
  {
    id: '6',
    rank: 6,
    title: 'Ask HN: What should every developer know about security?',
    url: undefined,
    source: undefined,
    points: 1456,
    author: 'security_advocate',
    time: '10 hours ago',
    comments: 634,
    category: 'Security',
    upvoted: false,
  },
  {
    id: '7',
    rank: 7,
    title: 'Optimizing database queries: practical tips from the field',
    url: 'https://example.com/db-optimization',
    source: 'example.com',
    points: 1289,
    author: 'db_expert',
    time: '11 hours ago',
    comments: 189,
    category: 'Databases',
    upvoted: false,
  },
  {
    id: '8',
    rank: 8,
    title: 'A deep dive into container orchestration: Kubernetes alternatives',
    url: 'https://tech-blog.example.com/k8s-alternatives',
    source: 'tech-blog.example.com',
    points: 1124,
    author: 'devops_pro',
    time: '12 hours ago',
    comments: 276,
    category: 'DevOps',
    upvoted: false,
  },
  {
    id: '9',
    rank: 9,
    title: 'The economics of open source: how projects sustain themselves',
    url: 'https://example.com/oss-economics',
    source: 'example.com',
    points: 987,
    author: 'open_source_guru',
    time: '13 hours ago',
    comments: 203,
    category: 'Open Source',
    upvoted: false,
  },
  {
    id: '10',
    rank: 10,
    title: 'Remote work in tech: what we learned after 5 years',
    url: 'https://company.example.com/remote-work-learnings',
    source: 'company.example.com',
    points: 856,
    author: 'remote_culture',
    time: '14 hours ago',
    comments: 421,
    category: 'Culture',
    upvoted: false,
  },
];

export const mockPostsByCategory = {
  top: mockPosts,
  new: mockPosts.slice().reverse(),
  ask: mockPosts.filter((p) => !p.url),
  show: mockPosts.filter((p) => p.source?.includes('github') || p.category === 'Startups'),
  jobs: [
    {
      id: 'j1',
      rank: 1,
      title: 'Senior Backend Engineer - Golang/Rust at early-stage startup',
      url: 'https://jobs.example.com/backend-engineer',
      source: 'jobs.example.com',
      points: 89,
      author: 'startup_jobs',
      time: '2 days ago',
      comments: 12,
      category: 'Jobs',
      upvoted: false,
    },
    {
      id: 'j2',
      rank: 2,
      title: 'ML Engineer - San Francisco (Remote OK) - serious AI team',
      url: 'https://jobs.example.com/ml-engineer',
      source: 'jobs.example.com',
      points: 76,
      author: 'ai_startup',
      time: '2 days ago',
      comments: 8,
      category: 'Jobs',
      upvoted: false,
    },
  ],
};
