#!/usr/bin/env bash
# Copy HN++ source to /Users/paddy/Desktop/v0-copy for manual upload to v0/Vercel.
# Run from project root: bash scripts/copy-to-v0.sh

set -e

SRC="$(cd "$(dirname "$0")/.." && pwd)"
DEST="/Users/paddy/Desktop/v0-copy"

echo "Source : $SRC"
echo "Dest   : $DEST"
echo ""

# Clean slate
rm -rf "$DEST"
mkdir -p "$DEST"

# ── Source code ──────────────────────────────────────────
rsync -a "$SRC/app/"        "$DEST/app/"
rsync -a "$SRC/components/" "$DEST/components/"
rsync -a "$SRC/lib/"        "$DEST/lib/"
rsync -a "$SRC/hooks/"      "$DEST/hooks/"
rsync -a "$SRC/styles/"     "$DEST/styles/"
rsync -a "$SRC/public/"     "$DEST/public/"

# ── Config files ─────────────────────────────────────────
cp "$SRC/package.json"        "$DEST/package.json"
cp "$SRC/next.config.mjs"     "$DEST/next.config.mjs"
cp "$SRC/tsconfig.json"       "$DEST/tsconfig.json"
cp "$SRC/components.json"     "$DEST/components.json"
cp "$SRC/postcss.config.mjs"  "$DEST/postcss.config.mjs"
cp "$SRC/tailwind.config.ts"  "$DEST/tailwind.config.ts"
cp "$SRC/next-env.d.ts"       "$DEST/next-env.d.ts"
cp "$SRC/pnpm-lock.yaml"      "$DEST/pnpm-lock.yaml"

# ── .gitignore ───────────────────────────────────────────
cat > "$DEST/.gitignore" <<'EOF'
node_modules/
.next/
.podcast-store/
*.tsbuildinfo
.env
.env.local
EOF

# ── .env.example ─────────────────────────────────────────
cat > "$DEST/.env.example" <<'EOF'
# Copy to .env.local and fill in values

# ElevenLabs — https://elevenlabs.io/app/settings/api-keys
ELEVENLABS_API_KEY=

# Firecrawl — https://www.firecrawl.dev/account
FIRECRAWL_API_KEY=

# Google Gemini — https://aistudio.google.com/apikey
GEMINI_API_KEY=

# Podcast cron auth — any strong random string
CRON_SECRET=

# ── Vercel deployment note ────────────────────────────────
# PODCAST_STORE_DIR is NOT set here on purpose.
# On Vercel, the filesystem is ephemeral (/tmp wiped on cold start).
# Episodes generated by the cron will survive within the same warm instance
# but will NOT persist across deployments or cold starts.
#
# For persistent episode storage, wire up Vercel Blob:
#   1. Enable Blob in your Vercel project dashboard
#   2. Add BLOB_READ_WRITE_TOKEN to env vars
#   3. Rewrite lib/podcast-store.ts to use @vercel/blob
#
# For hackathon demo purposes: leave PODCAST_STORE_DIR unset.
# The cron will write to /tmp/.podcast-store each warm instance.
# Set PODCAST_STORE_DIR=/tmp/.podcast-store explicitly if needed.
PODCAST_STORE_DIR=/tmp/.podcast-store
EOF

# ── Vercel config (cron) ──────────────────────────────────
cat > "$DEST/vercel.json" <<'EOF'
{
  "crons": [
    {
      "path": "/api/podcast/cron",
      "schedule": "30 13 * * *"
    }
  ]
}
EOF

echo ""
echo "✓ Copied to $DEST"
echo ""
echo "⚠️  IMPORTANT — before deploying:"
echo "   1. Add env vars in Vercel dashboard (see .env.example)"
echo "   2. The podcast cron in vercel.json needs CRON_SECRET — Vercel Cron"
echo "      calls the route directly; add auth check or use Vercel Cron secret header."
echo "   3. Podcast store uses /tmp — episodes reset on cold start."
echo "      For persistence, rewrite lib/podcast-store.ts with @vercel/blob."
echo ""
echo "Files ready. Upload v0-copy/ to v0 or push to GitHub and import in Vercel."
